### PR TITLE
Add PR Template

### PR DESCRIPTION
**Pull request by miankhalid**
This PR aims to add some default text while creating a PR through GitHub. After this is merged, following will be the result:

Before | After
--- | ---
screen shot 2017-08-10 at 1 14 43 pm | screen shot 2017-08-10 at 1 17 30 pm

### CODE REVIEW

**Comment by wahibhaq** [comment]
@miankhalid is this something you wrote specifically for this repo or something you already use at office? 

I think we need to create a very generic template with very basic and general questions. what do you thing? 

Btw, thanks for the effort 👍

**Comment by miankhalid** [comment]
Its inspired from my work repo but I tailored it to what I thought would give this repo's PRs a nice kickstart out-of-the-box.

Feel free to recommend any changes/improvements.

**Comment by wahibhaq** [comment]
@miankhalid This is a mini version of what we have. What do you say about it? 

## Description

* Describe what was implemented 

## To test

* Describe steps about how to test 

## Checklist

- [x] Logically structured commits
- [x] Tests added
- [x] Tested on device
- [x] No regressions (no crashes or critical bugs)

Good job, you made a kick-ass Pull Request. Now go find somebody to review it. :+1:

**Comment by miankhalid** [comment]
@wahibhaq great one!

Just 2 questions:

1 - The checklist checkboxes will be checked by default?
2 - If yes, then will the reviewer/s uncheck them if something's found missing?

**Comment by wahibhaq** [comment]
@miankhalid Oh No. They will be unchecked by default. It was wrongly copied.

**Comment by miankhalid** [comment]
@wahibhaq updated the PR template.

p.s. Sorry for the delay, was having some issues with my credentials and command line other than my laziness.

**Review by wahibhaq — APPROVED** [review]

**Pull request merged**
